allEasings = {
	-- Basic
	playdate.easingFunctions.linear,
	playdate.easingFunctions.inQuad,
	playdate.easingFunctions.outQuad,
	playdate.easingFunctions.inOutQuad,
	playdate.easingFunctions.outInQuad,
	playdate.easingFunctions.inCubic,
	playdate.easingFunctions.outCubic,
	playdate.easingFunctions.inOutCubic,
	playdate.easingFunctions.outInCubic,
	playdate.easingFunctions.inQuart,
	playdate.easingFunctions.outQuart,
	playdate.easingFunctions.inOutQuart,
	playdate.easingFunctions.outInQuart,
	playdate.easingFunctions.inQuint,
	playdate.easingFunctions.outQuint,
	playdate.easingFunctions.inOutQuint,
	playdate.easingFunctions.outInQuint,
	playdate.easingFunctions.inSine,
	playdate.easingFunctions.outSine,
	playdate.easingFunctions.inOutSine,
	playdate.easingFunctions.outInSine,
	playdate.easingFunctions.inExpo,
	playdate.easingFunctions.outExpo,
	playdate.easingFunctions.inOutExpo,
	playdate.easingFunctions.outInExpo,
	playdate.easingFunctions.inCirc,
	playdate.easingFunctions.outCirc,
	playdate.easingFunctions.inOutCirc,
	playdate.easingFunctions.outInCirc,
	playdate.easingFunctions.outBounce,
	playdate.easingFunctions.inBounce,
	playdate.easingFunctions.inOutBounce,
	playdate.easingFunctions.outInBounce,
	-- Elastic
	playdate.easingFunctions.inElastic,
	playdate.easingFunctions.outElastic,
	playdate.easingFunctions.inOutElastic,
	playdate.easingFunctions.outInElastic,
	-- Overshoot
	playdate.easingFunctions.inBack,
	playdate.easingFunctions.outBack,
	playdate.easingFunctions.inOutBack,
	playdate.easingFunctions.outInBack,
}

easingNames = {
	-- Basic
	"linear",
	"inQuad",
	"outQuad",
	"inOutQuad",
	"outInQuad",
	"inCubic",
	"outCubic",
	"inOutCubic",
	"outInCubic",
	"inQuart",
	"outQuart",
	"inOutQuart",
	"outInQuart",
	"inQuint",
	"outQuint",
	"inOutQuint",
	"outInQuint",
	"inSine",
	"outSine",
	"inOutSine",
	"outInSine",
	"inExpo",
	"outExpo",
	"inOutExpo",
	"outInExpo",
	"inCirc",
	"outCirc",
	"inOutCirc",
	"outInCirc",
	"outBounce",
	"inBounce",
	"inOutBounce",
	"outInBounce",
	-- Elastic
	"inElastic",
	"outElastic",
	"inOutElastic",
	"outInElastic",
	-- Overshoot
	"inBack",
	"outBack",
	"inOutBack",
	"outInBack",
}
